org.gradle.jvmargs=-Xmx4g -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false
android.useAndroidX=true
android.enableJetifier=true
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000
org.gradle.configuration-cache=false
android.ndkVersion=27.0.12077973